---
substitutions:
  gpio_led: GPIO9
  # For water one of: CCF, ft³, gal, L, m³
  volume_unit: 'gal'

packages:
  water_meter: !include
    file: esphome-magnetometer.yaml
    vars:
      device_class: 'water'
      device_icon: 'mdi:water'

switch:
  # LED flashes faster/slower as magnet rotates on water meter
  - platform: gpio
    id: led
    pin:
      number: ${gpio_led}
      inverted: true
